version: 2.1
orbs:
  macos: circleci/macos@2.3.2
jobs:
  test:
    macos:
      xcode: 13.4.1
    steps:
      - checkout
      - run: echo HELLO
      - run: xcodebuild -version
      - run: brew install watchman
      - run: brew tap wix/brew
      - run: brew install applesimutils
      - run: npm ci
      - run:
          command: pod install
          working_directory: "ios"
      - run: $(npm bin)/detox build -c ios
      - run: $(npm bin)/detox test -c ios
      - store_artifacts:
          path: detox_artifacts
          destination: detox_artifacts
workflows:
  version: 2.1
  test:
    jobs:
      - test
