version: 2.1
#orbs:
#  macos: circleci/macos@2.3.2

orbs:
  react-native: react-native-community/react-native@7.1.1
jobs:
  e2e_test:
    executor:
      name: macos
      xcode_version: 13.4.1
    steps:
      - checkout
      - rn/yarn_install
      - rn/pod_install
      - detox_build:
          configuration: ios
      - detox_test:
          configuration: ios
      - store_artifacts:
          path: detox_artifacts
          destination: detox_artifacts
workflows:
  version: 2.1
  test:
    jobs:
      - e2e_test
