version: 2.1
orbs:
  macos: circleci/macos@2.3.2
jobs:
  test:
    macos:
      xcode: "13.4.1"
    steps:
      - checkout
      - run: echo HELLO
workflows:
  version: 2.1
  test:
    jobs:
      - test
